### ISSUE TITLE
Trim Subnet CIDR While Creating Virtual Link

### ISSUE THREAD

**Issue by tunahanertekin** [robolaunch/central-orchestrator#71]
### What happened?

While creating a cloud instance, a virtual link job is being executed with manifest:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: add-vl
  labels:
    app: add-vl
spec:
  template:
    spec:
      # robolaunch tenancy labels
      nodeSelector:
        robolaunch.io/cloud-instance: <CLOUD-INSTANCE>
        robolaunch.io/department: <DEPARTMENT>
        robolaunch.io/organization: <ORGANIZATION>
        robolaunch.io/super-cluster: <SUPER-CLUSTER>
      containers:
      - image: nicolaka/netshoot:latest
        command: [ "/bin/bash", "-c", "--" ]
        #args: [ "ip link add subnet-3 type dummy; ip addr add 10.10.103.0/32 brd + dev subnet-3 label subnet-3:0; ip link set dev subnet-3 up;" ]
        args: [ "ip link add <subnet-id> type dummy; ip addr add <subnet-network-address>/32 brd + dev <subnet-id> label <subnet-id>:0; ip link set dev <subnet-id> up;" ]
        imagePullPolicy: IfNotPresent
        name: add-vl
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_ADMIN"]
          runAsUser: 0
      restartPolicy: Never
      hostNetwork: true
```

Since the input `<subnet-network-address>` is gathered from cloud instance's subnet's `spec.cidrBlock` field, orchestrator sets the value wrong such as `10.10.1.0/24/32`. Job seems completed but it returns error log.

### What did you expect to happen?

If the cloud instance cluster CIDR is `X.Y.Z.T/24`, I would expect orchestrator to set  `<subnet-network-address>` `X.Y.Z.T/32`. (`/32` is static postfix) And the job should be completed successfully.

### How can we reproduce it (as minimally and precisely as possible)?

After cloud instance creation, see logs of virtual link job:

```
kubectl logs -f pod/add-vl-<POD-POSTFIX>
```
